* The problem
  :PROPERTIES:
  :ID:       12E78AF7-4D86-480E-8ADF-6E210F79FFB6
  :END:

Every night at bedtime, I put on a movie and then fall asleep watching
it.  I used HandBrake to rip a lot of my DVDs that were good bedtime
movies (i.e. not loud action flicks).  But the problem I encountered
is that so many movies have at least a few REALLY LOUD parts that
would tend to wake me up.

I went searching for a way to make the really loud parts a little less
loud.

I am not familiar with audio processing and had a pretty hard time
figuring out how to find this stuff.

** DRC - Dynamic Range Control
   :PROPERTIES:
   :ID:       1A5D1680-E127-4066-B721-9CEA8FC185F8
   :END:

The first thing I found was the DRC flag in handbrake.  I ran into two
problems with this setting.

  - it seems to be hard-wired into the video.  I didn't want to apply
    this setting to my entire video collection, since I only wanted it
    turned on at bedtime.  So with this solution, I would need to have a
    separate 'bedtime' rip of each movie.  The advantage is that it works
    on any device that can play the media, e.g. a tablet.

  - even at the highest setting, this does not have a significant
    enough effect to keep from waking me up.

The results were that this was a no-go.

** Audio Hijack Pro
   :PROPERTIES:
   :ID:       3AF26F25-49C0-40DB-A435-2F0854126FE9
   :END:

I already owned a copy of Audio Hijack Pro that I have used for other
purposes, and I was pretty sure it could help do the trick.  But it
took me a while to find the secret sauce.

The disadvantage to this solution is that you have to play the media
on a computer that can run Audio Hijack Pro.  This won't work on your
tablet or smartphone.

** first attempt: AUPeakLimiter
   :PROPERTIES:
   :ID:       49504BE2-4ED8-4ACF-9DE7-BA806CBF97A9
   :END:

AudioUnit Effect => Apple => AUPeakLimiter

This plugin is designed to clip audio above a certain volume.  If you
watch in the editor window, you can see when audio gets above the
level and is being clipped.  It is not really intuitive how this
works--when you want to clip at a lower volume level, you have to
crank up the gain in order to pump up the audio so the clipping kicks
in earlier.  The easiest way to accomplish this is to use the pre-gain
in the AUPeakLimiter editor.  I found that around 20 is a pretty good
level to keep a loud scene in a movie from waking me up.

The downside of this solution is that the audio is very obviously
clipped.  If it is just a couple of loud noises then it is not bad,
but when it kicks in on loud music in movies, it is very annoying and
is really hard to listen to.

For a long time, this was the only thing I used, before I discovered
AUMultibandCompressor.


** solution: AUMultibandCompressor
   :PROPERTIES:
   :ID:       5EDEB361-4B76-41E4-9123-D62D40D71072
   :END:

AudioUnit Effect => Apple => AUMultibandCompressor

This plugin will actually reshape the volume curve, so as the media
volume is increasing significantly, the output will only increase
slightly.

The editor window provides a lot of options to control the volume
curve at different bands.  I didn't really play around with the curves
much--I went directly to Details and adjusted the Pre-Gain up to
around 25, and then set the post-gain to around 25.  This has the
effect of slightly pumping up the low volume bits while scaling down
the high volume bits.  It's perfect!

I still use the AUPeakLimiter plugin after the AUMultibandCompressor.
That way I can still ensure that any loud volumes that manage to get
through the AUMultibandCompressor will still get clipped.  When
watching the editor window in the AUPeakLimiter, I can see that very
little clipping is happening when I play a few loud scenes.
